version: '3'
services:
  phage-rabbitmq:
    image: rabbitmq
    networks: 
      - phage-net 

  phage-postgres:
    image: postgres:9.6.5
    ports:
      - "5432:5432"
    networks: 
      - phage-net 

  phage-web:
    build: .
    command: bundle exec rails server
    ports:
      - "3000:3000"
    links:
      - phage-postgres
      - phage-rabbitmq
      - visualizer
    volumes:
      - .:/app
    environment:
      DOCKER: docker
      RAILS_ENV: development
    env_file: .env 
    networks: 
      - phage-net 

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - phage-net

networks:
  phage-net:
