version: '3'
services:
  phage-rabbitmq:
    image: rabbitmq
    networks: 
      - phage-net 

  phage-postgres:
    image: postgres:9.6.5
    ports:
      - "5432:5432"
    networks: 
      - phage-net 

  web:
    build: .
    command: bundle exec rails server --port 3000 --binding 0.0.0.0 -C /app/config/puma-docker.rb
#   command: bundle exec rails s -b 0.0.0.0 -p 6000 -C config/puma-docker.rb 
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - phage-postgres
      - phage-rabbitmq
      - visualizer
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
    env_file: .env 
    networks: 
      - phage-net 

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - phage-net

networks:
  phage-net:
