version: '2'
services:
  postgres:
    image: postgres:9.6.5
    ports:
      - "5432:5432"

  web:
    build: .
    command: bundle exec rails server --port 3000 --binding 0.0.0.0 -C /app/config/puma-docker.rb
#   command: bundle exec rails s -b 0.0.0.0 -p 6000 -C config/puma-docker.rb 
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - postgres
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
