source 'https://rubygems.org'

gem 'capistrano', '~> 3.8'
gem 'capistrano-rails', '~> 1.2'
gem 'capistrano-rbenv', '~> 2.1'
gem 'capistrano-nc', '~> 0.1'
gem 'capistrano3-puma'
gem 'whenever'
gem 'bugsnag'
