dependencies: []

galaxy_info:
  author: aelogica
  description: Setup puma
  company: AELOGICA
  license:
    - MIT
    - BSD
  min_ansible_version: 1.9
  platforms:
    - name: Ubuntu
      version:
        - trusty
        - xenial
  galaxy_tags:
    - development
    - rails