- name: Phage production servers playbook
  hosts: all 
  gather_facts: true
  become: true
  become_user: root
  vars:
    database_name: phage_production
    rbenv: 
      env: user
      version: v1.1.1
      default_ruby: 2.5.1
      rubies:
        - version: 2.5.1
    rbenv_users:  [ romkey, phage ]
    default_gems_file: files/default_gems
    rbenv_plugins:
      - { name: "rbenv-vars",
        repo: "https://github.com/rbenv/rbenv-vars.git",
        version: "v1.2.0" }
      - { name: "ruby-build",
          repo: "https://github.com/rbenv/ruby-build.git",
          version: "master" }
      - { name: "rbenv-default-gems",
          repo: "https://github.com/rbenv/rbenv-default-gems.git",
          version: "v1.0.0" }

    rabbitmq_enabled: yes
    rabbitmq_plugins:                       # Ensure the plugins is installed
      - rabbitmq_management
      - rabbitmq_mqtt
      - rabbitmq_tracing 
      - rabbitmq_top
      - rabbitmq_web_mqtt
    rabbitmq_users:                         # Ensure the users added
      - user: admin
        password: "{{ rabbitmq_admin_password }}"
        vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
      - user: phage
        password: "{{ rabbitmq_phage_password }}"
        vhost: phage
        read_priv: .*
        write_priv: .*
      - user: phage_jobs
        password: "{{ rabbitmq_phage_jobs_password }}"
        vhost: phage_jobs
        read_priv: .*
        write_priv: .*
    rabbitmq_vhosts: [ phage, phage_jobs ]                     # Ensure the vhosts are exists
    rabbitmq_users_remove:                  # Ensure the users removed
      - guest
          
  roles:
    - basics
    - bennojoy.ntp
    - name: yatesr.timezone
      timezone: America/Los_Angeles
      tags: timezone
    - users
    - name: tersmitten.ssh-keys
      ssh_keys_authorized_keys:
        - owner: phage
          src: files/ssh-keys/phage_authorized_keys.pub

    - name: geerlingguy.nodejs
      tags: node

    - name: geerlingguy.nginx
      tags: nginx

    - name: zzet.rbenv
      tags: ruby
      rbenv_users: [ "phage", "romkey" ]

#    - name:  aelogica.puma
#      puma_user: phage
#      puma_shared: /home/phage/phage/shared
#      puma_root: /home/phage/phage

#    - jasonj.beanstalkd

    - name: pwelch.avahi 
      avahi_useipv6:  yes 
      avahi_install_utils: true

    - name: env
      tags: env

    - name: ANXS.postgresql 
      tags: postgresql
      postgresql_version: 10
      postgresql_databases:
        - name: "{{ database_name }}"
          owner: phage
          hstore: yes
      postgresql_users:
        - name: phage
          db: phage
          pass: "{{ database_user_password_encrypted }}"
          encrypted: yes
        - name: postgresql
          pass: "{{ database_admin_password_encrypted }}"
          encrypted: yes
          priv: "ALL"

    - name: Stouts.rabbitmq
      tags: rabbitmq
