- name: Phage Vagrant playbook
  hosts: all 
  gather_facts: true
  become: true
  become_user: root
  vars:
    database_name: phage_vagrant
    database_user_password: foobarfoobar
    database_admin_password: foobarfoobargo
    devise_prod_secret_key_base: 9489b3eee4eccba17ed77407233e8adc97baca7c74dc7ee33cd93e4c8b69477eea66eaedeb18af0be2679887c7c69c0a28c0fded0a71ea472a8c4laalal19cb
    smtp_server_address: 127.0.0.1
    smtp_domain: example.com
    smtp_username: nobody
    smtp_password: nothing
    bugsnag_api_key: foo
  roles:
    - basics
    - bennojoy.ntp
    - yatesr.timezone
    - users
    - name: tersmitten.ssh-keys
      ssh_keys_authorized_keys:
        - owner: phage
          src: files/ssh-keys/phage_authorized_keys.pub

    - name: ANXS.postgresql
      postgresql_version: 9.6
      postgresql_databases:
        - name: "{{ database_name }}"
          owner: phage
          hstore: yes
      postgresql_users:
        - name: phage
          db: "{{ database_name }}"
          pass: "{{ database_user_password }}"
          encrypted: no
        - name: postgresql
          pass: "{{ database_admin_password }}"
          encrypted: no
          priv: "ALL"
    - name: zzet.rbenv
      env: user
      default_ruby: "{{ ruby_version }}"
      rubies:
        - version: "{{ ruby_version }}"
      rbenv_plugins:
        - { name: "rbenv-vars",
            repo: "https://github.com/rbenv/rbenv-vars.git",
            version: "v1.2.0" }
        - { name: "ruby-build",
            repo: "https://github.com/rbenv/ruby-build.git",
            version: "master" }
        - { name: "rbenv-default-gems",
            repo: "https://github.com/rbenv/rbenv-default-gems.git",
            version: "v1.0.0" }
      rbenv_users: [ "phage" ]

    - jasonj.beanstalkd

    - name: pwelch.avahi 
      avahi_useipv6:  yes 
      avahi_install_utils: true 
    - name: env
